<?php

use Illuminate\Support\Facades\Route;
use App\Models\Movie;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    $movies=Movie::all();
    return view('welcome', compact('movies'));
})->name('welcome');

Route::resource('/movies', \App\Http\Controllers\MovieController::class )->parameters([
    'movies'=>'movies:slug',
]);

Route::get('/tvshows', function () {
    return view('tvshows');
})->name('tvshows');
Route::get('/actors', function () {
    return view('actors');
})->name('actors');


// Original variant generated by jetstream
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::view('/testmid', 'testmid')->name('testpage');


Route::view('/alpine', 'alpineview');


